### ISSUE TITLE
Link to maputnik not working

### ISSUE THREAD

**Issue by Tobeyforce** [jpriebe/google-maps-gl-style#3]
Hey,
Really curious on what your style looks like, but the link to maputnik doesn't work for me, it just loads it in blank.
Am I doing something wrong?

**Comment by jpriebe** [comment]
I'm guessing something has changed at maputnik.  I'm too far removed from this project now to be of much help, but you can see the style on this map:

https://www.wral.com/news-near-me/13696752/

**Comment by Tobeyforce** [comment]
Wow that looks so much better than the osm-liberty & bright, it's a real shame that you don't maintain it, it's a great idea :(
Anyone else who could help out on how to set this up?

**Comment by jpriebe** [comment]
You'll need to get a tile server set up: https://github.com/maptiler/tileserver-gl

Once you have that working (non-trivial), I think it's just a simple matter of configuration to add the style to it.

Good luck!
